### ISSUE TITLE
TypeError: getattr() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by diman82** [python-llfuse/python-llfuse#20]
I get this error when I try to copy one file to gridfs mounted directory:

```
-bash-4.2$ cp /home/dm57337/input/grid.zip /home/dm57337/output/
2018-10-16 07:13:27,253 - llfuse - INFO - handler raised <type 'exceptions.TypeError'> exception (getattr() takes exactly 2 arguments (3 given)), terminating main loop.
cp: failed to access ‘/home/dm57337/output/’: Input/output error
-bash-4.2$ Traceback (most recent call last):
  File "/usr/bin/gridfs_fuse", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/gridfs_fuse/main.py", line 265, in main
    init(args, configure=configure_parser, validate=validate_options)  # defaults
  File "/usr/lib/python2.7/site-packages/gridfs_fuse/main.py", line 260, in init
    run_fuse_mount(ops, options, mount_opts)
  File "/usr/lib/python2.7/site-packages/gridfs_fuse/main.py", line 209, in run_fuse_mount
    if 'single' in opts and opts['single'] is None:
  File "src/fuse_api.pxi", line 328, in llfuse.main
  File "src/handlers.pxi", line 80, in llfuse.fuse_getattr
  File "src/handlers.pxi", line 81, in llfuse.fuse_getattr
TypeError: getattr() takes exactly 2 arguments (3 given)
```
I mount the directory with the following command:
`gridfs_fuse -m /home/dm57337/output/ -u mongodb://admin_mongodb:p2fzzhYU@someremotehost:37017/admin.ImageFiles -d datasync_aws_poc -c ImageFiles `

What can be the problem?

**Comment by Nikratio** [comment]
Most likely the problem is Gridfs - you should report it there :-).

**Comment by diman82** [comment]
@Nikratio can you please suggest what would be the easiest way to debug "src/handlers.pxi" Cython source code? I couldn't find anything out of otder while debugginf gridfs_fuse/main.py file..

**Comment by Nikratio** [comment]
The problem isn't in handlers.pxi, but in the your code. You are probably defining your getattr() handler the wrong way.
