### ISSUE TITLE
llfuse-1.4.0 pytest failed with OverflowError

### ISSUE THREAD

**Issue by dfateyev** [python-llfuse/python-llfuse#60]
The "llfuse-1.4.0" release build failed with the error below, on `i686` and `armv7hl` architectures. 
```
+ py.test-3 -v test
============================= test session starts ==============================
platform linux -- Python 3.9.1, pytest-6.0.2, py-1.10.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /builddir/build/BUILD/llfuse-1.4.0/test, configfile: pytest.ini
collecting ... collected 15 items
test/test_api.py::test_inquire_bits PASSED                               [  6%]
test/test_api.py::test_listdir PASSED                                    [ 13%]
test/test_api.py::test_sup_groups PASSED                                 [ 20%]
test/test_api.py::test_entry_res PASSED                                  [ 26%]
test/test_api.py::test_xattr PASSED                                      [ 33%]
test/test_api.py::test_copy PASSED                                       [ 40%]
test/test_examples.py::test_lltest SKIPPED                               [ 46%]
test/test_examples.py::test_tmpfs SKIPPED                                [ 53%]
test/test_examples.py::test_passthroughfs SKIPPED                        [ 60%]
test/test_fs.py::test_invalidate_entry SKIPPED                           [ 66%]
test/test_fs.py::test_invalidate_inode SKIPPED                           [ 73%]
test/test_fs.py::test_notify_store SKIPPED                               [ 80%]
test/test_fs.py::test_entry_timeout SKIPPED                              [ 86%]
test/test_fs.py::test_attr_timeout SKIPPED                               [ 93%]
test/test_rounding.py::test_rounding FAILED                              [100%]
=================================== FAILURES ===================================
________________________________ test_rounding _________________________________
Traceback (most recent call last):
  File "/builddir/build/BUILD/llfuse-1.4.0/test/test_rounding.py", line 31, in test_rounding
    entry.st_atime_ns = total
  File "src/misc.pxi", line 474, in llfuse.EntryAttributes.st_atime_ns.__set__
    self.attr.st_atime = val // _NANOS_PER_SEC
OverflowError: Python int too large to convert to C long
=========================== short test summary info ============================
FAILED test/test_rounding.py::test_rounding - OverflowError: Python int too l...
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
==================== 1 failed, 6 passed, 8 skipped in 1.21s ====================
```

**Comment by ThomasWaldmann** [comment]
Hmm, looks like "only" on 32bit platforms?

**Comment by ThomasWaldmann** [comment]
@Grunthos @Nikratio see above. maybe also affects same patch in pyfuse3?

**Comment by ThomasWaldmann** [comment]
some stuff i found (seems there is no out-of-the-box 32bit support on github actions / travis-ci) :
- https://github.com/obspy/obspy/pull/1580/files
- https://github.com/nim-lang/Nim/pull/11337/files
- https://github.com/git/git/commit/88dedd5e72c082b741744c393567d7e5b4d03241

**Comment by Nikratio** [comment]
Looks like either `NANOS_PER_SEC` or the test value does not fit into 32 bit. This probably affects pyfuse3 as well. If someone cares enough about 32 bit systems to fix this then I don't mind merging a pull request. It's probably enough to force Cython to convert the value to `unsigned long long` rather than `long` - but I am not sure at which point the conversion currently takes place and where the target type comes from.

**Comment by Nikratio** [comment]
("src/misc.pxi", line 474 is where the fix needs to go, and probably the same for the other two time conversions below)

**Comment by ThomasWaldmann** [comment]
related: #61

**Comment by Grunthos** [comment]
Trying to get my head around the wider implications: does this mean there are likely to be runtime failures on llfuse if the underlying file system uses nano-seconds? Does it further mean that the FS will NOT use nanos on 32 bit systems? If so, then the test code could be bypassed on such systems, since it is irrelevant.

This is confusing.

**Comment by dfateyev** [comment]
Not sure which approach will be more logical in perspective, but would like to point out that the issue with test is blocking a new version provision to 32-bit systems right now. As long as popular distributions still provide 32-bit support, makes sense to support it too.

**Comment by ThomasWaldmann** [comment]
@Grunthos does your test require testing with 100 years? I suspect we might have a y2038 problem there due to signedness.

If it is that, it could be solved by using 67 years (1970 + 67 = 2037) in the test.

**Comment by ThomasWaldmann** [comment]
```
>>> secs = 67 * 365 * 24 * 3600 + 999
>>> nanos = 999999999
>>> total = secs * 1000000000 + nanos
>>> total / 1000000000         # old code, before the rounding fix
2112913000.0
>>> total // 1000000000       # fixed code
2112912999
>>> _ / (2**31)          # staying below 2**31 ?
0.983901787083596
```

**Comment by ThomasWaldmann** [comment]
@dfateyev could you modify `test_rounding.py` 100 -> 67 and run the tests again?

**Comment by ThomasWaldmann** [comment]
#62 has the potential fix, please test / review (I don't have any 32bit system).

**Comment by Grunthos** [comment]
Looks like a simple and effective approach to me! 100 years was arbitrary. Change to any value that makes sense!

**Comment by ThomasWaldmann** [comment]
@Grunthos ok, if 100y was arbitrary, guess 67 will do it better (by avoiding y2038) - I have merged PR #62 into master to simplify testing.

**Comment by dfateyev** [comment]
Tested against the repository's HEAD:
```
+ py.test-3 -v test
============================= test session starts ==============================
platform linux -- Python 3.9.1, pytest-6.0.2, py-1.10.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /builddir/build/BUILD/llfuse-1.4.1/test, configfile: pytest.ini
collecting ... collected 15 items
test/test_api.py::test_inquire_bits PASSED                               [  6%]
test/test_api.py::test_listdir PASSED                                    [ 13%]
test/test_api.py::test_sup_groups PASSED                                 [ 20%]
test/test_api.py::test_entry_res PASSED                                  [ 26%]
test/test_api.py::test_xattr PASSED                                      [ 33%]
test/test_api.py::test_copy PASSED                                       [ 40%]
test/test_examples.py::test_lltest SKIPPED                               [ 46%]
test/test_examples.py::test_tmpfs SKIPPED                                [ 53%]
test/test_examples.py::test_passthroughfs SKIPPED                        [ 60%]
test/test_fs.py::test_invalidate_entry SKIPPED                           [ 66%]
test/test_fs.py::test_invalidate_inode SKIPPED                           [ 73%]
test/test_fs.py::test_notify_store SKIPPED                               [ 80%]
test/test_fs.py::test_entry_timeout SKIPPED                              [ 86%]
test/test_fs.py::test_attr_timeout SKIPPED                               [ 93%]
test/test_rounding.py::test_rounding PASSED                              [100%]
========================= 7 passed, 8 skipped in 0.23s =========================
```
@ThomasWaldmann the test results under 32-bit look good now, thanks!
if there are no objections, could you prepare a new minor release with this fix?

**Comment by ThomasWaldmann** [comment]
Thanks for testing, yes I'll make a new release.

**Comment by ThomasWaldmann** [comment]
1.4.1 is released!
