### ISSUE TITLE
tmpfs example fs test failure on macOS / macFUSE

### ISSUE THREAD

**Issue by ThomasWaldmann** [python-llfuse/python-llfuse#84]
```
(python-llfuse-env) tw@mba2020 python-llfuse % pytest -k tmpfs test                                        
============================================================================= test session starts ==============================================================================
platform darwin -- Python 3.11.3, pytest-7.3.1, pluggy-1.0.0 -- /Users/tw/w/python-llfuse-env/bin/python3.11
cachedir: .pytest_cache
rootdir: /Users/tw/w/python-llfuse/test
configfile: pytest.ini
collected 15 items / 14 deselected / 1 selected                                                                                                                                

test/test_examples.py::test_tmpfs FAILED                                                                                                                                 [100%]

=================================================================================== FAILURES ===================================================================================
__________________________________________________________________________________ test_tmpfs __________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/tw/w/python-llfuse/test/test_examples.py", line 76, in test_tmpfs
    tst_mkdir(mnt_dir)
  File "/Users/tw/w/python-llfuse/test/test_examples.py", line 142, in tst_mkdir
    os.mkdir(fullname)
OSError: [Errno 5] Input/output error: '/private/var/folders/61/qtqwzmxd7t1fb19zck5k3q0h0000gn/T/pytest-of-tw/pytest-3/test_tmpfs0/testfile_2'
=============================================================================== warnings summary ===============================================================================
test/conftest.py:41
  /Users/tw/w/python-llfuse/test/conftest.py:41: PytestDeprecationWarning: The hookimpl pytest_pyfunc_call uses old-style configuration options (marks or attributes).
  Please use the pytest.hookimpl(hookwrapper=True) decorator instead
   to configure the hooks.
   See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
    @pytest.mark.hookwrapper

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================================================================== short test summary info ============================================================================
FAILED test/test_examples.py::test_tmpfs - OSError: [Errno 5] Input/output error: '/private/var/folders/61/qtqwzmxd7t1fb19zck5k3q0h0000gn/T/pytest-of-tw/pytest-3/test_tmpfs0/testfile_2'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================= 1 failed, 14 deselected, 1 warning in 1.17s ==================================================================
```

**Comment by ThomasWaldmann** [comment]
Even more strange: 

If I try out the tmpfs manually (just mounting it somewhere, then use misc. shell commands to try it out), it works.
